<?php echo $this->Doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
            <meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
            <?php 
            echo $this->headTitle();
            echo $this->headLink();
            echo $this->headScript();
            ?>
    </head>
    <body>
        <div id="page">
            <div id="header">
                <h1>Projeto Zend Framework</h1>
            </div>
            <div id="content">
                <?=$this->flashMessenger()?>
                <?php echo $this->layout()->content; ?>
            </div>

            <div id="rodape">
            <ul>
                    <li> Item one </li>
                    <li> Item two </li>
            </ul>
            </div>
        </div>
    </body>
</html>